ui <- dashboardPage(
  dashboardHeader(title = "Cluster Annotation"),
# Tab menu layout ---------------------------------------------------------
  sidebar <- dashboardSidebar(
    sidebarMenu(id = "tabs",
      menuItem("Load", tabName = "settings"),
      menuItem("Thresholds", tabName = "thresholds"),
      menuItem("Tree-Annotation", tabName = "treeannotation"),
      menuItem("UMAP interactive", tabName = "umap_reactive"),
      menuItem("UMAP Marker expression", tabName = "UMAP_Marker_expression"),
      menuItem("Differential Abundance", tabName = "DA_tab"),
      menuItem("DA interactive Tree", tabName = "DA_tree"),
      menuItem("Help", tabName = "help"))),
  dashboardBody(
    tags$head(tags$style("#thTableBox{height:400px !important;}")),
    tags$head(tags$style("#mytreebox{height:700px !important;}")),
    tabItems(
      tabItem(tabName = "settings",Settings_UI(id="Settings")),
      tabItem(tabName = "thresholds",Threshold_UI(id="threshold")),
      tabItem(tabName = "treeannotation",
              fluidRow(
                 column(width = 3,
                        box(width = NULL,TreeAnnotation_picker_UI(id="TreeAnnotation_picker"))),
                 column(width = 9,
                        fluidRow(
                          column(width = 4,
                          box(width = 12,title = "Node Select:",
                              column(width = 6,
                                     selectizeInput(inputId = ("parentPicker"),label = "Select Parent:",choices=NULL),
                                     actionButton(("deleteNodeBtn"), "Delete Node")),
                              column(width = 6,
                                     TreeAnnotation_valuebox_UI(id="TreeAnnotation_valuebox")))),
                          column(width = 4,
                          box(width = 12,title = "Create Node",
                              textInput(("newNode"), "Set Name..."),
                              actionButton(("createNodeBtn"), "Create Node"))),
                          column(width = 4,
                                 box(width = 12,title = "Export Annotation",
                                     TreeAnnotation_annotationdownload_UI(id="TreeAnnotation_annotationdownload")))),
                        fluidRow(
                          column(width = 6,
                                 box(width=12,title = "Annotation Tree",visNetwork_UI(id="visNetwork"))),
                          column(width = 6,
                        tabBox(width=12,
                               tabPanel(title = "Heatmap",Heatmap_UI(id="Heatmap")),
                               tabPanel(title = "Umap",Umap_UI(id="Umap")))))))),
      tabItem(tabName = "umap_reactive",umap_interactive_UI(id="umap_interactive")),
      tabItem(tabName = "UMAP_Marker_expression",UMAP_ME_UI(id="UMAP_ME")),
      tabItem(tabName = "DA_tab",Differential_Abundance_UI(id="Differential_Abundance")),
      tabItem(tabName = "DA_tree",
              fluidRow(
                column(width = 8,
                       box(id="mytreebox",width = NULL,title = "Interactive DA Tree",
                           visNetworkOutput("interactiveTree", width = "100%", height = "700px"))),
                DA_interactive_UI(id="DA_interactive"))))))
